!function(e){"use strict"
function t(){function t(t){return void 0===o[t]&&(o[t]=e(t)),o[t]}var o={}
return{get:t}}new t
Royal_Preloader.config({mode:"progress",background:"#161616",showProgress:!0,showPercentage:!1}),window.scrollReveal=new scrollReveal,e(window).scroll(function(){var t=e(".fade-elements"),o=e(this).scrollTop()
t.css({"margin-top":-(o/0)+"px",opacity:1-o/400})}),e(document).ready(function(){function t(t){e(".cd-nav-container, .cd-overlay").toggleClass("is-visible",t),e("main").toggleClass("scale-down",t)}function o(e,t){var o=document.getElementById("cd-zoom-in"),l=document.getElementById("cd-zoom-out")
e.appendChild(o),e.appendChild(l),google.maps.event.addDomListener(o,"click",function(){t.setZoom(t.getZoom()+1)}),google.maps.event.addDomListener(l,"click",function(){t.setZoom(t.getZoom()-1)})}var l=450,r=500
jQuery(window).scroll(function(){jQuery(this).scrollTop()>l?jQuery(".scroll-to-top").fadeIn(r):jQuery(".scroll-to-top").fadeOut(r)}),jQuery(".scroll-to-top").on("click",function(e){return e.preventDefault(),jQuery("html, body").animate({scrollTop:0},r),!1}),e(".tipped").tipper(),e(".cd-nav-trigger").on("click",function(e){e.preventDefault(),t(!0)}),e(".cd-close-nav, .cd-overlay").on("click",function(e){e.preventDefault(),t(!1)}),e(".cd-nav li").on("click",function(e){t(!1)}),e(".container").fitVids(),e(".vimeo a,.youtube a").on("click",function(t){t.preventDefault()
var o=e(this).attr("href"),l=(e(this).parent(),e(this).parent())
e(this).parent().hasClass("youtube")?(e(this).parent().wrapAll('<div class="video-wrapper">'),e(l).html('<iframe frameborder="0" height="333" src="'+o+'?autoplay=1&showinfo=0" title="YouTube video player" width="547"></iframe>')):(e(this).parent().wrapAll('<div class="video-wrapper">'),e(l).html('<iframe src="'+o+'?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1&amp;color=21d365" width="500" height="281" frameborder="0"></iframe>'))})
var n=48.735351,s=2.295592,a=10,i=navigator.userAgent.toLowerCase().indexOf("trident")>-1,c=i?"images/cd-icon-location.png":"images/cd-icon-location.svg",p=[{featureType:"all",elementType:"labels.text.fill",stylers:[{saturation:36},{color:"#000000"},{lightness:40}]},{featureType:"all",elementType:"labels.text.stroke",stylers:[{visibility:"on"},{color:"#000000"},{lightness:16}]},{featureType:"all",elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"administrative",elementType:"geometry.fill",stylers:[{color:"#000000"},{lightness:20}]},{featureType:"administrative",elementType:"geometry.stroke",stylers:[{color:"#000000"},{lightness:17},{weight:1.2}]},{featureType:"landscape",elementType:"geometry",stylers:[{color:"#000000"},{lightness:20}]},{featureType:"poi",elementType:"geometry",stylers:[{color:"#000000"},{lightness:21}]},{featureType:"road.highway",elementType:"geometry.fill",stylers:[{color:"#000000"},{lightness:17}]},{featureType:"road.highway",elementType:"geometry.stroke",stylers:[{color:"#000000"},{lightness:29},{weight:.2}]},{featureType:"road.arterial",elementType:"geometry",stylers:[{color:"#000000"},{lightness:18}]},{featureType:"road.local",elementType:"geometry",stylers:[{color:"#000000"},{lightness:16}]},{featureType:"transit",elementType:"geometry",stylers:[{color:"#000000"},{lightness:19}]},{featureType:"water",elementType:"geometry",stylers:[{color:"#000000"},{lightness:17}]}],y={center:new google.maps.LatLng(n,s),zoom:a,panControl:!1,zoomControl:!1,mapTypeControl:!1,streetViewControl:!1,mapTypeId:google.maps.MapTypeId.ROADMAP,scrollwheel:!1,styles:p},m=new google.maps.Map(document.getElementById("google-container"),y),g=(new google.maps.Marker({position:new google.maps.LatLng(n,s),map:m,visible:!0,icon:c}),document.createElement("div"))
new o(g,m)
m.controls[google.maps.ControlPosition.LEFT_TOP].push(g)})}(jQuery)