# load some routes - one should ultimately have the path "/app"
app:
    resource: '@AppBundle/Controller/'
    type: annotation

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /portfolio
        permanent: true